name: linux ubuntu build

on:
  push

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get Information Variables
        id: core
        run: |
          echo "platform=$(uname -m)" >> $GITHUB_OUTPUT
          echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Run build
        run: |
          make dep exe
          mkdir -p ${{ github.workspace }}/artifact
          mv main.dist ${{ github.workspace }}/artifact/asteroids-linux-${{ steps.core.outputs.platform }}-${{ steps.core.outputs.sha8 }}
          
      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: asteroids-linux-${{ steps.core.outputs.platform }}-${{ steps.core.outputs.sha8 }}
          path: ${{ github.workspace }}/artifact/**/*